### ISSUE TITLE
Unity loses all serialized references of generic scriptable objects after git pull

### ISSUE THREAD

**Issue by JingHaoYao** [SolidAlloy/GenericUnityObjects#24] opened 2021-10-20 02:54 UTC
Hi Artem! Sorry to be a sore thorn in your side at this point. We've been using your plugin extensively and we've come across this issue with version control.

It seems that when I push any changes to master (which includes the assemblies generated in the GenericUnityObjects folder) and one of my teammates pulls it, all prefabs or objects that have references to that generic scriptable object are lost. 

![image](https://user-images.githubusercontent.com/23221908/138020417-c5f090c4-3d24-410d-80af-9b73cf60ca9d.png)

The scriptable objects that lose reference are still there but they also seem to be corrupted.

**Comment by SolidAlloy** [comment] 2021-10-20 19:39
Hi! No worries, it's my goal to make the plugin work properly in all scenarios :)

Could you check the generated assembly related to the `ScriptablePropertyValue<Vector2>` type? It should be called **ScriptablePropertyValue_Vector2.dll**. Does it contain a class inside like in the screenshot?
![image](https://user-images.githubusercontent.com/22909454/138157730-56e92c06-f18c-4f2d-b1ba-09935b7063c6.png)

Second-of-all, I see there is ConcreteClass_... instead of the real script file in the Script field of `ScriptablePropertyValueHolder`. Do you use a custom editor? You can use `GenericUnityObjectHelper` in it to draw the Script field properly. Check out the `GenericUnityObjectEditor` class to see how it is used.

Could you check if the changes to the **SOGenerationDatabase** asset were submitted in the same commit with the **ScriptablePropertyValue_Vector2.dll** asset? This scriptable object keeps references to all newly generated assemblies and usually shows up in the changes list along with the .dll files. If it somehow didn't end up in the same commit as **ScriptablePropertyValue_Vector2.dll**, it could be a hint on what happened.

Finally, can you please ask your colleague to provide the **EditorResources/SOGenerationDatabase** and **Resources/ScriptableObjectsDatabase** assets? They can give an insight into why the reference was corrupted. They contain the names of the generic classes you use in the project, so if it is confidential information, you can send them via email instead.

**Comment by JingHaoYao** [comment] 2021-10-20 20:13
Hi Artem,

My friend got back to me, he mentioned that there isn't a **ScriptablePropertyValue_Vector2.dll**, but something called **ScriptablePropertyValue_Vector2_1.dll** instead. 

![image](https://user-images.githubusercontent.com/23221908/138164148-a8182b1f-7825-4d26-92ef-dc6811d791aa.png)

And yes we use a lot of custom editors to draw the components we make for our game! I'll take a look at GenericUnityObjectEditor! Thanks for the pointer. 

I always make sure to commit all plugin files whenever I commit, but yes I commited SOGenerationDatabase with the dll asset with it. 

I'm not sure how to attach files in comments here - so I'll send them over by email!

**Comment by SolidAlloy** [comment] 2021-10-22 21:35
Thank you for the files. I found out there are no `ScriptablePropertyValue<Vector2>` and `ScriptablePropertyValue<Vector2Int>` in the databases, although I can see in the screenshot that the DLLs for them were created. Could you check what lines were added to the **SOGenerationDatabase.asset** and **ScriptableObjectsDatabase.asset** files when you committed **ScriptablePropertyValue_Vector2_1.dll** to the repository?

As I understand, not all generic scriptable objects are corrupted when they are pulled from the repository. Most of the references are kept when someone pulls changes from the repository, and only some references are corrupted like in the case of `ScriptablePropertyValue<Vector2>`, right? I would really like to find a consistent reproduce of the issue. If you have any ideas about what was different in the case of `ScriptablePropertyValue<Vector2>`, I'd love to hear them.

**Comment by JingHaoYao** [comment] 2021-10-22 23:22
Yes, not all generic scriptable objects created have this issue. In terms of the lines that were commited: 

SOGenerationDatabase.asset:
![image](https://user-images.githubusercontent.com/23221908/138532687-a1449df2-7d07-4984-9e13-e32c1f191080.png)
![image](https://user-images.githubusercontent.com/23221908/138532696-a306d846-2fba-4a06-b71f-bfd05040af9d.png)

ScriptableObjectsDatabase.asset:
![image](https://user-images.githubusercontent.com/23221908/138532733-ffa2eccb-e7a7-41a1-a09e-89c02311c445.png)

I remember some of the lost references we fixed by reimporting all the DLLs in the plugins folder. But as for any differences with that commit, I'm not sure.

**Comment by SolidAlloy** [comment] 2021-10-24 19:24
Thanks for the screenshots. Judging by them, the assemblies generated for `ScriptablePropertyValue<Vector2>` and `ScriptablePropertyValue<Vector2Int>` were not in the database at the moment of the commit. I'll investigate how exactly it could happen. Could you check the name and GUID of the `ScriptablePropertyValue<Vector2>` assembly you committed? Was it called "ScriptablePropertyValue_Vector2.dll" or "ScriptablePropertyValue_Vector2_1.dll" at the time? Is the GUID of the .dll asset you committed the same as the GUID of **ScriptablePropertyValue_Vector2_1.dll** on your teammate's side?

**Comment by SolidAlloy** [comment] 2021-10-24 21:31
While I was investigating the issue, I submitted a few small fixes. I doubt they fixed this particular bug, but they can facilitate the investigation should the bug reoccur, so I recommend you update your version of GenericUnityObjects to 2.11.4

**Comment by JingHaoYao** [comment] 2021-10-24 21:44
Hi, I'll update the plugin! But as for your questions: 
The name of the assembly is ScriptablePropertyValueHolder_Vector2_1.dll, and the GUID is f42f2052c91a1b544afa66b96b570b66 on master, however my friend has a GUID of f830314fa3fb1be4b92037afc5657939

**Comment by JingHaoYao** [comment] 2021-10-24 21:52
We also have these cases where the references are set in Prefabs but they lose their reference in scene. 

Scene:
![image](https://user-images.githubusercontent.com/23221908/138614420-548d4071-dd3c-4b10-8ba5-22e84815a91c.png)
Prefab:
![image](https://user-images.githubusercontent.com/23221908/138614428-2fae5301-5c40-41c4-ac72-3af27449b161.png)

**Comment by SolidAlloy** [comment] 2021-10-25 19:27
Thanks, I just realized I haven't accounted for a situation when both of the teammates generate an assembly for the same type (e.g. `ScriptablePropertyValueHolder<Vector2>`). I'll check how to resolve such merge conflicts. I doubt that's what happened to you because the assemblies have the same suffix. Most likely, the .dll asset changed its GUID after it was pulled. I'm still wondering how it could happen, so more ways to reproduce the bug are appreciated.

**Comment by SolidAlloy** [comment] 2021-10-25 19:38
As for prefabs, it could be a bug inside Unity and not related to the plugin. I stumbled upon it recently in 2020.3.19, so it can be present in all recent versions of Unity. In such cases, I remove the reference inside the prefab and assign it again - then the prefab starts working properly again. I don't see any changes in the .prefab file in git after that, so it's probably related to AssetDatabase and its cache. Try this workaround and let me know if there are any changes to the .prefab file after you reassign the reference. I haven't figured out a precise way to reproduce the bug, so I can't report it to Unity yet.

**Comment by SolidAlloy** [comment] 2021-10-29 15:21
Hi, I checked the commits in your project and found the following:
- In commit f789e527b5d6317df9b1d94007b51ebcf7aedbee, **tmastant** created **ScriptablePropertyValue_Vector2_1.dll**, and it was added to **SOGenerationDatabase.asset** in the same commit.
- In commit a0df62e78017769d58d1499b9948af06876ade01, the branch was merged and **ScriptablePropertyValue_Vector2_1.dll** made it into the merge commit, but **SOGenerationDatabase.asset** didn't :(

So, the plugin worked but the data was lost during the merge. Such things happen from time to time and we need to restore the data whenever possible. I partly fixed this issue in [this commit](https://github.com/SolidAlloy/GenericUnityObjects/commit/1e88e3cd93882f5ec8c89b6cad437b967eee0197). How it works: if you generate a concrete class assembly but the data is somehow lost in the database, the next time you create an asset of this type, the missing data will be detected and restored.

I'm also planning to search for all the generated assemblies that are located in **Plugins/GenericUnityObjects/Assemblies/** but are not in the database, and add them back there. But it's a bigger feature and will take some time.

Meanwhile, you can keep using the plugin as a situation like with `ScriptablePropertyValue<Vector2>` shouldn't happen again because it was fixed in 2.11.4

**Comment by SolidAlloy** [comment] 2021-11-21 19:33
Hey Jing, I added the feature I talked about in the previous comment. Now, if the .dll file is committed without **SOGenerationDatabase** for some reason, it will be detected and added back to the database. Please try the **2.13.1** version of the package

**Closed as completed** 2021-12-01 09:28 UTC
